{% set name = "qtpynodeeditor" %}
{% set version = "0.3.2" %}
{% set sha256 = "d3933cca107cfc83dc87971310b244e4587e0c76a2d472a75f04cd41001d0e7d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm
    - setuptools
  run:
    - python >={{ python_min }}
    - qtpy
    - pyqt
    - qt

test:
  requires:
    - python {{ python_min }}
  imports:
    - qtpynodeeditor
    - qtpynodeeditor.examples
    - qtpynodeeditor.tests

about:
  home: https://github.com/klauer/qtpynodeeditor
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python Qt node editor
  doc_url: https://klauer.github.io/qtpynodeeditor/

extra:
  recipe-maintainers:
    - klauer
