{% set name = "qtpynodeeditor" %}
{% set version = "0.3.0" %}
{% set sha256 = "141acb0ba5ef84a03efdbe4d88db0a46facf00449a6542492d9b585aa9931bda" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools_scm
  run:
    - python >=3.9
    - qtpy
    - pyqt
    - qt

test:
  imports:
    - qtpynodeeditor
    - qtpynodeeditor.examples
    - qtpynodeeditor.tests

about:
  home: https://github.com/klauer/qtpynodeeditor
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python Qt node editor
  doc_url: https://klauer.github.io/qtpynodeeditor/

extra:
  recipe-maintainers:
    - klauer
