{% set name = "qtpynodeeditor" %}
{% set version = "0.2.0" %}
{% set sha256 = "5201d4d52115ebf67a066c969442cce49c1b541635fc6c77a526724c1bca7916" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - qtpy
    - pyqt
    - qt

test:
  imports:
    - qtpynodeeditor
    - qtpynodeeditor.examples
    - qtpynodeeditor.tests

about:
  home: https://github.com/klauer/qtpynodeeditor
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python Qt node editor
  doc_url: https://klauer.github.io/qtpynodeeditor/

extra:
  recipe-maintainers:
    - klauer
